In [24]:
import pandas as pd

import seaborn as sns

from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LogisticRegression  

from sklearn.metrics import mean_absolute_error,r2_score

In [25]:
titanicdf = sns.load_dataset('titanic')
titanicdf.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [26]:
survived_factorized = pd.factorize(titanicdf['sex'])
titanicdf['survived_factorized'] = survived_factorized[0]

titanicdf.head(2)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,survived_factorized
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,0
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,1

In [27]:
X = titanicdf[['fare']] #
y = titanicdf['survived_factorized']

In [29]:
model_Logistic = LogisticRegression()
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.2, random_state = 42)

model_Logistic.fit(X_train,y_train)

y_pred = model_Logistic.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0])

In [34]:
#evaluate performance

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# confusion matrix 

cm = confusion_matrix(y_test,y_pred)
print(cm)

accuracy_test = accuracy_score(y_test, y_pred)
print(accuracy_test)



cr = classification_report(y_test,y_pred)
print(cr)

[[109   1]
 [ 65   4]]
0.6312849162011173
              precision    recall  f1-score   support

           0       0.63      0.99      0.77       110
           1       0.80      0.06      0.11        69

    accuracy                           0.63       179
   macro avg       0.71      0.52      0.44       179
weighted avg       0.69      0.63      0.51       179

In [31]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[109,   1],
       [ 65,   4]])

In [32]:
accuracy_test = accuracy_score(y_test, y_pred)
accuracy_test

0.6312849162011173