***One hot encoding***

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np

In [2]:
iris = sns.load_dataset('iris')
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
df_onehot=pd.get_dummies(iris, columns=['species']) # get dummies automatically ignores any missing values
df_onehot['species_setosa']

0       True
1       True
2       True
3       True
4       True
       ...
145    False
146    False
147    False
148    False
149    False
Name: species_setosa, Length: 150, dtype: bool

In [5]:
penguins = sns.load_dataset('penguins')
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

In [9]:
#get dummies method - categories -->
penguins_onehot = pd.get_dummies(penguins, columns=['species'])
penguins_onehot['species_Adelie']

0       True
1       True
2       True
3       True
4       True
       ...
339    False
340    False
341    False
342    False
343    False
Name: species_Adelie, Length: 344, dtype: bool

In [13]:
penguins_onehot

,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_Adelie,species_Chinstrap,species_Gentoo
0,Torgersen,39.1,18.7,181.0,3750.0,Male,True,False,False
1,Torgersen,39.5,17.4,186.0,3800.0,Female,True,False,False
2,Torgersen,40.3,18.0,195.0,3250.0,Female,True,False,False
3,Torgersen,NaN,NaN,NaN,NaN,NaN,True,False,False
4,Torgersen,36.7,19.3,193.0,3450.0,Female,True,False,False
...,...,...,...,...,...,...,...,...,...
339,Biscoe,NaN,NaN,NaN,NaN,NaN,False,False,True
340,Biscoe,46.8,14.3,215.0,4850.0,Female,False,False,True
341,Biscoe,50.4,15.7,222.0,5750.0,Male,False,False,True
342,Biscoe,45.2,14.8,212.0,5200.0,Female,False,False,True
343,Biscoe,49.9,16.1,213.0,5400.0,Male,False,False,True

In [14]:
iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [ ]:
df = pd.DataFrame([1,2,1,1,np.nan,3,3,3,2,2,2,1,1,1], columns=['first']) 
df.head()

df['first'].dtype

df['first'] = df['first'].astype('category')
df['first'].dtype
df_encoded = pd.get_dummies(df, columns=['first'],dummy_na=True) # dummyna will display the nan
df_encoded.head()

   first_1.0  first_2.0  first_3.0  first_nan
0       True      False      False      False
1      False       True      False      False
2       True      False      False      False
3       True      False      False      False
4      False      False      False       True

In [30]:
penguins_onehot = pd.get_dummies(penguins)
penguins_onehot

,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,species_Adelie,species_Chinstrap,species_Gentoo,island_Biscoe,island_Dream,island_Torgersen,sex_Female,sex_Male
0,39.1,18.7,181.0,3750.0,True,False,False,False,False,True,False,True
1,39.5,17.4,186.0,3800.0,True,False,False,False,False,True,True,False
2,40.3,18.0,195.0,3250.0,True,False,False,False,False,True,True,False
3,NaN,NaN,NaN,NaN,True,False,False,False,False,True,False,False
4,36.7,19.3,193.0,3450.0,True,False,False,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
339,NaN,NaN,NaN,NaN,False,False,True,True,False,False,False,False
340,46.8,14.3,215.0,4850.0,False,False,True,True,False,False,True,False
341,50.4,15.7,222.0,5750.0,False,False,True,True,False,False,False,True
342,45.2,14.8,212.0,5200.0,False,False,True,True,False,False,True,False
343,49.9,16.1,213.0,5400.0,False,False,True,True,False,False,False,True

In [ ]:
penguins_onehot = pd.get_dummies(penguins, columns=['species'])
penguins_onehot['species_Adelie']

penguins_onehot = pd.get_dummies(penguins,columns=['island','species'])
penguins_onehot

0       True
1       True
2       True
3       True
4       True
       ...
339    False
340    False
341    False
342    False
343    False
Name: island_Torgersen, Length: 344, dtype: bool

In [ ]:
##can also use sklearn.preprocessing method

In [49]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

pl, pw, sl, sw, species, setosa, virginica, versicolor

Species --> object
drop the column betfore fitting into the model

In [ ]:
iris_onehot=iris.copy()

#create the onehotencoder  # returns nump array  #
encoder = OneHotEncoder(sparse_output=False,handle_unknown='ignore') 

categorical_cols = ['species']

iris_onehot = encoder.fit_transform(iris_onehot[categorical_cols])

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [51]:
penguins_onehot=penguins.copy()

#create the onehotencoder  # returns nump array  #
encoder = OneHotEncoder(sparse_output=False,handle_unknown='ignore') 

categorical_cols = ['species']

penguins_onehot = encoder.fit_transform(penguins_onehot[categorical_cols])
penguins_onehot

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]], shape=(344, 3))

In [57]:
iris_onehot=iris.copy()

#create the onehotencoder  # returns nump array  #
encoder = OneHotEncoder(sparse_output=False,handle_unknown='ignore') 

categorical_cols = ['species']

encoded_values = encoder.fit_transform(iris_onehot[categorical_cols])

#name of new column that dont exist
new_col = encoder.get_feature_names_out(categorical_cols)
new_col
#'species_setosa', 'species_versicolor', 'species_virginica'],


iris_onehot[new_col] = encoded_values
iris_onehot

iris_onehot.drop(columns=['species'],inplace=True)
iris_onehot

,sepal_length,sepal_width,petal_length,petal_width,species_setosa,species_versicolor,species_virginica
0,5.1,3.5,1.4,0.2,1.0,0.0,0.0
1,4.9,3.0,1.4,0.2,1.0,0.0,0.0
2,4.7,3.2,1.3,0.2,1.0,0.0,0.0
3,4.6,3.1,1.5,0.2,1.0,0.0,0.0
4,5.0,3.6,1.4,0.2,1.0,0.0,0.0
...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,0.0,0.0,1.0
146,6.3,2.5,5.0,1.9,0.0,0.0,1.0
147,6.5,3.0,5.2,2.0,0.0,0.0,1.0
148,6.2,3.4,5.4,2.3,0.0,0.0,1.0
149,5.9,3.0,5.1,1.8,0.0,0.0,1.0

In [ ]:
# try on diff dataset

Try to do both.
Label encoding, and one hot encoding on
 
titanic dataset