In [3]:

import seaborn as sns

import pandas as pd

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier, plot_tree

from sklearn.metrics import classification_report

In [4]:
tipsdf = sns.load_dataset('tips')
tipsdf.head(2)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

In [5]:
smoker_bin = pd.factorize(tipsdf['smoker'])
tipsdf['smoker_bin'] = smoker_bin[0]
tipsdf.head(2)

   total_bill   tip     sex smoker  day    time  size  smoker_bin
0       16.99  1.01  Female     No  Sun  Dinner     2           0
1       10.34  1.66    Male     No  Sun  Dinner     3           0

In [6]:
X = tipsdf[['total_bill']]
y = tipsdf['smoker_bin']

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X,y)

model_knn = KNeighborsClassifier()
model_dt = DecisionTreeClassifier()

model_knn.fit(X_train, y_train)
model_dt.fit(X_train, y_train)

y_pred_knn = model_knn.predict(X_test)
y_pred_dt = model_dt.predict(X_test)

In [13]:
cr_knn = classification_report(y_test,y_pred_knn)

print(cr_knn)

cr_dt = classification_report(y_test,y_pred_dt)

print(cr_dt)

              precision    recall  f1-score   support

           0       0.59      0.81      0.68        37
           1       0.30      0.12      0.18        24

    accuracy                           0.54        61
   macro avg       0.44      0.47      0.43        61
weighted avg       0.47      0.54      0.48        61

              precision    recall  f1-score   support

           0       0.64      0.68      0.66        37
           1       0.45      0.42      0.43        24

    accuracy                           0.57        61
   macro avg       0.55      0.55      0.55        61
weighted avg       0.57      0.57      0.57        61