In [1]:
import pandas as pd
import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt

import plotly.express as px

In [2]:
crimedf = pd.read_csv("C:\\Users\\user\\Desktop\\aiml\\Daily-Practice\\Day 9 - Practice Data Analysis\\crime_district.csv")
crimedf.head()

      state district category type        date  crimes
0  Malaysia      All  assault  all  2016-01-01   22327
1  Malaysia      All  assault  all  2017-01-01   21366
2  Malaysia      All  assault  all  2018-01-01   16902
3  Malaysia      All  assault  all  2019-01-01   16489
4  Malaysia      All  assault  all  2020-01-01   13279

In [ ]:
# to drop the first row from dataset which are the results of everything
# drop_malaysia = crimedf[crimedf['state'] == 'Malaysia'].index
# crimedf.drop(drop_malaysia, inplace=True)

In [ ]:
# to drop the index and starts with 0
# crimedf.reset_index(drop=True,inplace=True)
# crimedf

In [3]:
#change data type of date from string
crimedf['date'] = pd.to_datetime(crimedf['date'])
#extract the year
crimedf['date'] = crimedf['date'].dt.year
crimedf['date'] = crimedf['date'].astype(int)

In [4]:
crimedf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19152 entries, 0 to 19151
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   state     19152 non-null  object
 1   district  19152 non-null  object
 2   category  19152 non-null  object
 3   type      19152 non-null  object
 4   date      19152 non-null  int64
 5   crimes    19152 non-null  int64
dtypes: int64(2), object(4)
memory usage: 897.9+ KB

In [5]:
# filter Malaysia and years 2016–2023
malaysia_df = crimedf[
    (crimedf['state'] == 'Malaysia') &
    (crimedf['district'] == 'All') &
    (crimedf['date'].between(2016, 2023)) &
    (crimedf['category'].isin(['assault', 'property']))
]

malaysia_df.head(50)

       state district category                  type  date  crimes
0   Malaysia      All  assault                   all  2016   22327
1   Malaysia      All  assault                   all  2017   21366
2   Malaysia      All  assault                   all  2018   16902
3   Malaysia      All  assault                   all  2019   16489
4   Malaysia      All  assault                   all  2020   13279
5   Malaysia      All  assault                   all  2021   11495
6   Malaysia      All  assault                   all  2022   10348
7   Malaysia      All  assault                   all  2023   10453
8   Malaysia      All  assault        causing_injury  2016    5531
9   Malaysia      All  assault        causing_injury  2017    5024
10  Malaysia      All  assault        causing_injury  2018    4660
11  Malaysia      All  assault        causing_injury  2019    4712
12  Malaysia      All  assault        causing_injury  2020    4118
13  Malaysia      All  assault        causing_injury  2021    4063
14  Malaysia      All  assault        causing_injury  2022    3807
15  Malaysia      All  assault        causing_injury  2023    3693
16  Malaysia      All  assault                murder  2016     456
17  Malaysia      All  assault                murder  2017     379
18  Malaysia      All  assault                murder  2018     323
19  Malaysia      All  assault                murder  2019     310
20  Malaysia      All  assault                murder  2020     253
21  Malaysia      All  assault                murder  2021     243
22  Malaysia      All  assault                murder  2022     240
23  Malaysia      All  assault                murder  2023     258
24  Malaysia      All  assault                  rape  2016    1886
25  Malaysia      All  assault                  rape  2017    1835
26  Malaysia      All  assault                  rape  2018    1648
27  Malaysia      All  assault                  rape  2019    1738
28  Malaysia      All  assault                  rape  2020    1582
29  Malaysia      All  assault                  rape  2021    1553
30  Malaysia      All  assault                  rape  2022    1712
31  Malaysia      All  assault                  rape  2023    1914
32  Malaysia      All  assault    robbery_gang_armed  2016      65
33  Malaysia      All  assault    robbery_gang_armed  2017      31
34  Malaysia      All  assault    robbery_gang_armed  2018      31
35  Malaysia      All  assault    robbery_gang_armed  2019      21
36  Malaysia      All  assault    robbery_gang_armed  2020       6
37  Malaysia      All  assault    robbery_gang_armed  2021       5
38  Malaysia      All  assault    robbery_gang_armed  2022      16
39  Malaysia      All  assault    robbery_gang_armed  2023      30
40  Malaysia      All  assault  robbery_gang_unarmed  2016   10907
41  Malaysia      All  assault  robbery_gang_unarmed  2017    9779
42  Malaysia      All  assault  robbery_gang_unarmed  2018    6543
43  Malaysia      All  assault  robbery_gang_unarmed  2019    6058
44  Malaysia      All  assault  robbery_gang_unarmed  2020    2992
45  Malaysia      All  assault  robbery_gang_unarmed  2021    3071
46  Malaysia      All  assault  robbery_gang_unarmed  2022    2432
47  Malaysia      All  assault  robbery_gang_unarmed  2023    2578
48  Malaysia      All  assault    robbery_solo_armed  2016      19
49  Malaysia      All  assault    robbery_solo_armed  2017       3

In [15]:
crime_countsdf = (malaysia_df.groupby(['category','date'])['crimes'].sum().reset_index())
crime_countsdf
# crimes are groupby date and category

    category  date  crimes
0    assault  2016   44654
1    assault  2017   42732
2    assault  2018   33804
3    assault  2019   32978
4    assault  2020   26558
5    assault  2021   22990
6    assault  2022   20696
7    assault  2023   20906
8   property  2016  180056
9   property  2017  155608
10  property  2018  143520
11  property  2019  133934
12  property  2020  104688
13  property  2021   82958
14  property  2022   80930
15  property  2023   83982

In [ ]:

bargraph = px.bar(crime_countsdf, x='date', y='crimes', color='category', title='Crime Counts in Malaysia (2016–2023): Assault vs Property')    # barmode='group'
# pakai crime_countsdf, 
bargraph.show()

In [17]:
bystate_df = crimedf[
    (crimedf['district'] == 'All') &
    (crimedf['state'] != 'Malaysia') &
    (crimedf['type'] == 'all') &
    (crimedf['category'].isin(['assault','property']))
]

bystate_df

                   state district  category type  date  crimes
112                Johor      All   assault  all  2016    2820
113                Johor      All   assault  all  2017    2578
114                Johor      All   assault  all  2018    1880
115                Johor      All   assault  all  2019    1923
116                Johor      All   assault  all  2020    1384
...                  ...      ...       ...  ...   ...     ...
18435  W.P. Kuala Lumpur      All  property  all  2019    8258
18436  W.P. Kuala Lumpur      All  property  all  2020    6353
18437  W.P. Kuala Lumpur      All  property  all  2021    4718
18438  W.P. Kuala Lumpur      All  property  all  2022    3865
18439  W.P. Kuala Lumpur      All  property  all  2023    3600

[224 rows x 6 columns]

In [18]:
crimebystate_countsdf = (bystate_df.groupby(['state'])['crimes'].sum().reset_index())
crimebystate_countsdf

                state  crimes
0               Johor   65963
1               Kedah   43185
2            Kelantan   25348
3              Melaka   17980
4     Negeri Sembilan   23392
5              Pahang   22385
6               Perak   34352
7              Perlis    4019
8        Pulau Pinang   36653
9               Sabah   38944
10            Sarawak   43136
11           Selangor  157455
12         Terengganu   14984
13  W.P. Kuala Lumpur   77701

In [19]:
fig = px.bar(
    crimebystate_countsdf, x='state', y='crimes', color='state', title='Crime Counts in Malaysia (2016–2023) by states')    # barmode='group'
fig.show()

In [20]:
crimebystate_countsdf

                state  crimes
0               Johor   65963
1               Kedah   43185
2            Kelantan   25348
3              Melaka   17980
4     Negeri Sembilan   23392
5              Pahang   22385
6               Perak   34352
7              Perlis    4019
8        Pulau Pinang   36653
9               Sabah   38944
10            Sarawak   43136
11           Selangor  157455
12         Terengganu   14984
13  W.P. Kuala Lumpur   77701

In [ ]:
fig = px.imshow(crimebystate_countsdf)

In [ ]:
sns.lineplot(malaysia_df,x='date',y='crimes')
sns.set(style='darkgrid')

In [ ]:
sns.jointplot(malaysia_df, x='date' , y='crimes')

In [ ]:
sns.boxenplot(malaysia_df,x='state',y='crimes')
sns.set(style='darkgrid')

#rc parameters
# runtime configurations
plt.rcParams["figure.figsize"]= (100, 60)
plt.rcParams['lines.linewidth'] = 3
plt.rcParams['lines.linestyle'] = '--'

In [ ]:
#rc parameters
plt.rcParams["figure.figsize"]= (10, 6)

In [ ]:
plt.scatter()

need to set global context!! use import matplot

In [ ]:
sns.set_theme(
    style='whitegrid',
    context='talk',
    rc={
        'figure.figsize':(8,4),
        'figure.dpi':120, # define pixel density resolution (density per ??)
        'axes.titlesize':12,
        'axes.labelsize': 10,
        'lines.linewidth':2,
        'lines.linestyle' :'--',
    }
)

In [ ]:
sns.histplot(crimedf,x='state')
sns.set_theme(
    style='whitegrid',
    context='talk',
    rc={
        'figure.figsize':(8,4),
        'figure.dpi':120, # define pixel density resolution (density per ??)
        'axes.titlesize':12,
        'axes.labelsize': 10,
        'lines.linewidth':2,
        'lines.linestyle' :'--',
    }
)

In [ ]:
#plotly 
mean = crimedf['crimes'].mean()
px.bar(crimedf, x='state', y=)