In [19]:
import pandas as pd
import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt

import plotly.express as px

In [62]:
crimedf = pd.read_csv("C:\\Users\\user\\Desktop\\aiml\\Daily-Practice\\Day 9 - Practice Data Analysis\\crime_district.csv")
crimedf.head()

      state district category type        date  crimes
0  Malaysia      All  assault  all  2016-01-01   22327
1  Malaysia      All  assault  all  2017-01-01   21366
2  Malaysia      All  assault  all  2018-01-01   16902
3  Malaysia      All  assault  all  2019-01-01   16489
4  Malaysia      All  assault  all  2020-01-01   13279

In [ ]:
# to drop the first row from dataset which are the results of everything
# drop_malaysia = crimedf[crimedf['state'] == 'Malaysia'].index
# crimedf.drop(drop_malaysia, inplace=True)

In [ ]:
# to drop the index and starts with 0
# crimedf.reset_index(drop=True,inplace=True)
# crimedf

,state,district,category,type,date,crimes
0,Johor,All,assault,all,2016-01-01,2820
1,Johor,All,assault,all,2017-01-01,2578
2,Johor,All,assault,all,2018-01-01,1880
3,Johor,All,assault,all,2019-01-01,1923
4,Johor,All,assault,all,2020-01-01,1384
...,...,...,...,...,...,...
19035,W.P. Kuala Lumpur,Wangsa Maju,property,theft_vehicle_motorcycle,2019-01-01,755
19036,W.P. Kuala Lumpur,Wangsa Maju,property,theft_vehicle_motorcycle,2020-01-01,646
19037,W.P. Kuala Lumpur,Wangsa Maju,property,theft_vehicle_motorcycle,2021-01-01,403
19038,W.P. Kuala Lumpur,Wangsa Maju,property,theft_vehicle_motorcycle,2022-01-01,369
19039,W.P. Kuala Lumpur,Wangsa Maju,property,theft_vehicle_motorcycle,2023-01-01,358

In [63]:
#change data type of date from string
crimedf['date'] = pd.to_datetime(crimedf['date'])
#extract the year
crimedf['date'] = crimedf['date'].dt.year
crimedf['date'] = crimedf['date'].astype(int)

In [64]:
crimedf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19152 entries, 0 to 19151
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   state     19152 non-null  object
 1   district  19152 non-null  object
 2   category  19152 non-null  object
 3   type      19152 non-null  object
 4   date      19152 non-null  int64
 5   crimes    19152 non-null  int64
dtypes: int64(2), object(4)
memory usage: 897.9+ KB

In [71]:
# filter Malaysia and years 2016–2023
malaysia_df = crimedf[
    (crimedf['state'] == 'Malaysia') &
    (crimedf['district'] == 'All') &
    (crimedf['date'].between(2016, 2023)) &
    (crimedf['category'].isin(['assault', 'property']))
]

malaysia_df

        state district  category                      type  date  crimes
0    Malaysia      All   assault                       all  2016   22327
1    Malaysia      All   assault                       all  2017   21366
2    Malaysia      All   assault                       all  2018   16902
3    Malaysia      All   assault                       all  2019   16489
4    Malaysia      All   assault                       all  2020   13279
..        ...      ...       ...                       ...   ...     ...
107  Malaysia      All  property  theft_vehicle_motorcycle  2019   22501
108  Malaysia      All  property  theft_vehicle_motorcycle  2020   16059
109  Malaysia      All  property  theft_vehicle_motorcycle  2021    9944
110  Malaysia      All  property  theft_vehicle_motorcycle  2022   10457
111  Malaysia      All  property  theft_vehicle_motorcycle  2023   10588

[112 rows x 6 columns]

In [ ]:
crime_counts = (malaysia_df.groupby(['category','date'])['crimes'].sum().reset_index())
# groupby date and category

In [68]:
fig = px.bar(
    crime_counts,
    x='date',
    y='crimes',
    color='category',
    barmode='group',
    title='Crime Counts in Malaysia (2013–2016): Assault vs Property'
)

fig.show()

In [ ]:
sns.lineplot(crimedf,x='date',y='crimes')
sns.set(style='darkgrid')

In [ ]:
sns.jointplot(crimedf, x='' , y='',kind='')

In [ ]:
sns.boxenplot(crimedf,x='state',y='crimes')
sns.set(style='darkgrid')

#rc parameters
# runtime configurations
plt.rcParams["figure.figsize"]= (100, 60)
plt.rcParams['lines.linewidth'] = 3
plt.rcParams['lines.linestyle'] = '--'

In [ ]:
#rc parameters
plt.rcParams["figure.figsize"]= (10, 6)

In [ ]:
plt.scatter()

need to set global context!! use import matplot

In [ ]:
sns.set_theme(
    style='whitegrid',
    context='talk',
    rc={
        'figure.figsize':(8,4),
        'figure.dpi':120, # define pixel density resolution (density per ??)
        'axes.titlesize':12,
        'axes.labelsize': 10,
        'lines.linewidth':2,
        'lines.linestyle' :'--',
    }
)

In [ ]:
sns.histplot(crimedf,x='state')
sns.set_theme(
    style='whitegrid',
    context='talk',
    rc={
        'figure.figsize':(8,4),
        'figure.dpi':120, # define pixel density resolution (density per ??)
        'axes.titlesize':12,
        'axes.labelsize': 10,
        'lines.linewidth':2,
        'lines.linestyle' :'--',
    }
)

In [ ]:
#plotly 
mean = crimedf['crimes'].mean()
px.bar(crimedf, x='state', y=)