- house price

tips dataset

take numerical column only - input feature

if label encoding can do, take all column

appyl linear regrssion

target feature tips - target feature

In [ ]:
import pandas as pd

import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,LogisticRegression 

from sklearn.metrics import mean_absolute_error,r2_score

In [ ]:
tipsdf = sns.load_dataset('tips')
tipsdf.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
sex_factorized = pd.factorize(tipsdf['sex'])
tipsdf['sex_factorized'] = sex_factorized[0]

smoker_factorized = pd.factorize(tipsdf['smoker'])
tipsdf['smoker_factorized'] = smoker_factorized[0]

time_factorized = pd.factorize(tipsdf['time'])
tipsdf['time_factorized'] = time_factorized[0]

day_factorized = pd.factorize(tipsdf['day'])
tipsdf['day_factorized'] = day_factorized[0]

size_factorized = pd.factorize(tipsdf['size'])
tipsdf['size_factorized'] = size_factorized[0]
tipsdf

,total_bill,tip,sex,smoker,day,time,size,sex_factorized,smoker_factorized,time_factorized,day_factorized,size_factorized
0,16.99,1.01,Female,No,Sun,Dinner,2,0,0,0,0,0
1,10.34,1.66,Male,No,Sun,Dinner,3,1,0,0,0,1
2,21.01,3.50,Male,No,Sun,Dinner,3,1,0,0,0,1
3,23.68,3.31,Male,No,Sun,Dinner,2,1,0,0,0,0
4,24.59,3.61,Female,No,Sun,Dinner,4,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,1,0,0,1,1
240,27.18,2.00,Female,Yes,Sat,Dinner,2,0,1,0,1,0
241,22.67,2.00,Male,Yes,Sat,Dinner,2,1,1,0,1,0
242,17.82,1.75,Male,No,Sat,Dinner,2,1,0,0,1,0
243,18.78,3.00,Female,No,Thur,Dinner,2,0,0,0,2,0

In [ ]:
X = tipsdf[['total_bill','sex_factorized', 'smoker_factorized', 'time_factorized', 'day_factorized']]
y = tipsdf['tip']

In [ ]:
model = LinearRegression()
model_Logistic = LogisticRegression()

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.2, random_state = 42)

In [ ]:
model.fit(X_train,y_train)

LinearRegression()

In [ ]:
y_pred = model.predict(X_test)
y_pred

array([3.12264572, 1.96829866, 3.68426048, 3.53139907, 2.17586225,
       2.70871764, 3.8806019 , 2.37063159, 2.62184306, 2.26823918,
       3.00353038, 2.13852313, 2.17163222, 2.3379046 , 2.10856138,
       3.04048741, 2.82253419, 3.36129428, 2.730432  , 5.51838857,
       3.19150159, 3.21290227, 2.24640674, 2.00585688, 3.01028316,
       2.31047515, 2.1314129 , 3.43931556, 2.80779329, 6.25276607,
       5.15446351, 1.55771675, 2.90407263, 2.92243924, 2.83423946,
       3.63204839, 1.9297011 , 5.45010879, 2.44457671, 3.18124717,
       2.11024999, 2.59246696, 3.61901479, 2.11218708, 1.91235672,
       1.02413735, 1.84188342, 2.99976632, 1.86136727])

In [ ]:
r2 = r2_score(y_test, y_pred)  

mae = mean_absolute_error(y_test,y_pred)
mae 

print(f'r2 = {r2}\nmae = {mae}')

r2 = 0.48744417767692205
mae = 0.6379537501508385

In [ ]:
model.coef_

array([ 0.10874283,  0.02575039, -0.25131561,  0.11916981, -0.04726119])